# Generated by Django 2.0.6 on 2018-06-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
