# Generated by Django 2.0.6 on 2018-06-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
